name: Generate Keystore
on:
  workflow_dispatch:
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore options-analyst.jks \
            -alias options-analyst \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=LOSIEV YURII, OU=LOSIEV YURII, O=LOSIEV YURII, L=Tbilisi, S=Tbilisi, C=GE" \
            -storepass MyPass123! \
            -keypass MyPass123!
      - name: Print base64
        run: base64 options-analyst.jks
